### ISSUE TITLE
ckantoolkit - Python 3 support

### ISSUE THREAD

**Issue by amercader** [ckan/ckantoolkit#7]
- [ ] Update Circle CI setup to use Circle 2.0 (so the tests can run again). Or use Travis
- [ ] Run the tests on Python 2.7, 3.6, 3.7 and 3.8
- [ ] Fix any syntax or issues in the code base that prevent the library from running on Python 3

**Comment by shubham-mahajan** [comment]
@amercader I will take this one.

**Comment by shubham-mahajan** [comment]
@amercader Need to set up the project in CircleCI to do the building.

**Comment by amercader** [comment]
Fixed on #8
