### ISSUE TITLE
Update of this package for CKAN 2.9 ?

### ISSUE THREAD

**Issue by jerbou** [ckan/ckantoolkit#9]
hello,

We are a "final customer" of a CKAN version embedded in a project IDGO :
https://github.com/neogeo-technologies/idgo

the readme tells that this package is for future version, but the last version is really "compatible with" CKAN version 2.9 and Pytho 3.0 support ?
Otherwise, we could finance the update.

Best Regards,

Jérôme Boutet
IDéO BFC
https://ideo.ternum-bfc.fr/

**Comment by amercader** [comment]
Yes, this library should work with CKAN 2.9 and Python 3. If you find an issue while working with it don't hesitate to create an issue!

**Comment by jerbou** [comment]
thanks for the reply !
